version: '3.8'

services:

#######Partie Client########
  
  nginx-web:
    #site web présenté au client
    build: 
      context: .
      dockerfile: ./web-Dockerfile
    container_name: web
    volumes:
      #- /home/mapti89/Documents/LANPARTY-website/web:/usr/share/nginx/html
      - /home/mapti89/Documents/LANPARTY-website/data/xml:/usr/share/nginx/html/xml:ro
      - /home/mapti89/Documents/LANPARTY-website/data/torrent:/usr/share/nginx/html/torrent:ro
      - /home/mapti89/Documents/LANPARTY-website/data/data:/usr/share/nginx/html/data:ro
    ports:
      - "80:80"
    restart: unless-stopped
  
  opentracker:
    #tracker de torrent
    image: lednerb/opentracker-docker
    container_name: opentracker
    ports:
      - "6969:6969/udp"
      - "6969:6969"
    restart: unless-stopped

  nginx-webseed:
    #service web pour servir de HTTP seed, le mettre à part permet de le binder sur une carte réseau différente pour ne pas impacter le reste des services (optionnel)
    image: nginx
    container_name: httpseed
    volumes:
      - /home/mapti89/Documents/LANPARTY-website/data:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    restart: unless-stopped

#######Partie Admin########
  nginx-webadmin:
    #site web pour ajouter, supprimer, ou editer des jeux
    build: 
      context: .
      dockerfile: ./webadmin-Dockerfile
    container_name: web-admin
    #volumes:
      #- /home/mapti89/Documents/LANPARTY-website/webadmin:/usr/share/nginx/html
    ports:
      - "82:80"
    restart: unless-stopped

  torrent:
    #container qui construit les torrents
    build: 
      context: .
      dockerfile: ./torrent-Dockerfile
    container_name: torrent
    volumes:
      - /home/mapti89/Documents/LANPARTY-website/data/data:/usr/src/app/data:ro
      - /home/mapti89/Documents/LANPARTY-website/data/xml:/usr/src/app/xml
      - /home/mapti89/Documents/LANPARTY-website/data/torrent:/usr/src/app/torrent
    ports:
      - "5001:5001"
    networks:
      - backend
    restart: unless-stopped

  backend:
    #container qui sert de backend au site d'admin
    build: 
      context: .
      dockerfile: ./backend-Dockerfile
    container_name: backend
    volumes:
      - /home/mapti89/Documents/LANPARTY-website/data/data:/usr/src/app/data
      - /home/mapti89/Documents/LANPARTY-website/data/xml:/usr/src/app/xml
      - /home/mapti89/Documents/LANPARTY-website/data/torrent:/usr/src/app/torrent
    ports:
      - "5000:5000"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    name: backend
